# Generated by Django 3.1.7 on 2021-03-15 19:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 17, 19, 24, 43, 602982)),
        ),
    ]
