# Generated by Django 3.1.7 on 2021-03-15 22:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210315_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 17, 22, 12, 6, 751567)),
        ),
    ]
